import{S as f,i as d}from"./assets/vendor-7659544d.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const m="/goit-js-hw-11/assets/icon-06de2d57.svg";function h(s){const o="https://pixabay.com/api/",r="42554621-2fa4a31fb360b145b3c1613f4",i=new URLSearchParams({key:r,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}),e=`${o}?${i}`;return fetch(e).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()})}function p(s){return s.map(({webformatURL:o,largeImageURL:r,tags:i,likes:e,views:t,comments:n,downloads:u})=>`<li class="gallery-item">
                     <a href="${r}">
                        <img src="${o}" alt="${i}"/>
                        <div class="info-box">
                           <p class="info"><b>Likes</b> ${e}</p>
                           <p class="info"><b>Views</b> ${t}</p>
                           <p class="info"><b>Comments</b> ${n}</p>
                           <p class="info"><b>Downloads</b> ${u}</p>
                     </div>
                    </a>
                   </li>`).join("")}const l=document.querySelector("form"),c=document.querySelector("ul.gallery"),a=document.querySelector("span.loader");a.classList.remove("loader");function g(s){s.preventDefault(),c.innerHTML=null;const o=s.currentTarget.elements.search.value.trim();o!==""&&(a.classList.add("loader"),h(o).then(r=>{a.classList.remove("loader"),r.hits.length!==0?(c.innerHTML=p(r.hits),new f(".gallery a",{captionsData:"alt",captionDelay:100}).refresh()):d.show({iconUrl:m,message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#FFFFFF",color:"#FF6868",position:"topRight",progressBarColor:"#FFFFFF",close:!1,timeout:3e3})}).catch(r=>console.log(r))),l.reset()}l.addEventListener("submit",g);
//# sourceMappingURL=commonHelpers.js.map
